### PR TITLE
Cleaned up is_valid, tried (and failed) to enhance grid printing

### PR DESCRIPTION
**Pull request by IAmRasputin**
I'm trying to use "termcolor" such that when the grid is printed, there is an option to make the current position bold.  Either my terminal doesn't support it, or it's not working right yet.

And now I'm going to go to sleep.

### CODE REVIEW

**Comment by IAmRasputin** [comment]
I didn't merge this yet so you guys can take a look at it first and tell me if anything blows up.

**Comment by sarahbethfederman** [comment]
Go to sleep ryan

**Comment by jal5313** [comment]
This looks good. You cleaned up all the hacky work-arounds I had in there. Nice work!

**Comment by IAmRasputin** [comment]
Alright then, consider it merged.

**Pull request merged**
